=== MCDekitateServerRosen/dekitatete-train-data/routes_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "dekitate-train-data Routes Path Validate",
    "description": "Varidate dekitate-train-data path data",
    "properties": {
        "path":{
            "type":"array",
            "items": {
                "type":"object",
                "properties": {
                    "starts":{
                        "type":"array",
                        "items": {
                            "type":"number"
                        }
                    },
                    "ends":{
                        "type":"array",
                        "items": {
                            "type":"number"
                        }
                    },
                    "time":{
                        "type":"integer"
                    },
                    "movement":{
                        "type":"array",
                        "items": {
                            "type":"number"
                        }
                    }
                },
                "required": [
                    "starts",
                    "ends",
                    "time"
                ]
            }
        },
        "id":{
            "type":"string"
        },
        "time":{
            "type":"integer"
        },
        "updated":{
            "type":"integer"
        }
    },
    "required": [
        "id",
        "path",
        "time",
        "updated"
    ]
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/5b9f5b40-6f29-4621-ab4b-4d27b4286e72.json
{
    "id":"5b9f5b40-6f29-4621-ab4b-4d27b4286e72",
    "path": [
        {
            "starts": [
                44.0,
                3475.0
            ],
            "ends": [
                44.0,
                3473.0
            ],
            "time": 3,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                44.0,
                3001.0
            ],
            "ends": [
                44.0,
                3001.0
            ],
            "time": 1,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 69,
    "updated": 1679637908
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/5715d1f1-886c-4da9-b94a-f493d75b9e03.json
{
    "id":"5715d1f1-886c-4da9-b94a-f493d75b9e03",
    "path": [
        {
            "starts": [
                245.0,
                19.0
            ],
            "ends": [
                245.0,
                18.0
            ],
            "time": 3,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                245.0,
                17.0
            ],
            "ends": [
                246.0,
                -149.0
            ],
            "time": 20,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                246.0,
                -157.0
            ],
            "ends": [
                246.0,
                -165.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                246.0,
                -181.0
            ],
            "ends": [
                236.0,
                -428.0
            ],
            "time": 32,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                235.0,
                -435.0
            ],
            "ends": [
                235.0,
                -443.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                235.0,
                -451.0
            ],
            "ends": [
                237.0,
                -657.0
            ],
            "time": 25,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                245.0,
                -657.0
            ],
            "ends": [
                253.0,
                -655.0
            ],
            "time": 1,
            "movement": [
                1,
                1
            ]
        },
        {
            "starts": [
                269.0,
                -657.0
            ],
            "ends": [
                277.0,
                -657.0
            ],
            "time": 1,
            "movement": [
                1,
                0
            ]
        },
        {
            "starts": [
                285.0,
                -657.0
            ],
            "ends": [
                429.0,
                -658.0
            ],
            "time": 18,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                429.0,
                -674.0
            ],
            "ends": [
                429.0,
                -682.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                429.0,
                -690.0
            ],
            "ends": [
                431.0,
                -858.0
            ],
            "time": 20,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                429.0,
                -866.0
            ],
            "ends": [
                429.0,
                -874.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                429.0,
                -890.0
            ],
            "ends": [
                433.0,
                -1250.0
            ],
            "time": 45,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                433.0,
                -1255.0
            ],
            "ends": [
                433.0,
                -1255.0
            ],
            "time": 1,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 193,
    "updated": 1679638626
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/b8f24a06-3002-4297-b1f4-42a6f6bac41c.json
{
    "id":"b8f24a06-3002-4297-b1f4-42a6f6bac41c",
    "path": [
        {
            "starts": [
                -67.0,
                948.0
            ],
            "ends": [
                -57.0,
                918.0
            ],
            "time": 5,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                -49.0,
                910.0
            ],
            "ends": [
                -19.0,
                863.0
            ],
            "time": 6,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -19.0,
                847.0
            ],
            "ends": [
                -17.0,
                775.0
            ],
            "time": 8,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                -16.0,
                767.0
            ],
            "ends": [
                -16.0,
                759.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -8.0,
                756.0
            ],
            "ends": [
                8.0,
                756.0
            ],
            "time": 1,
            "movement": [
                1,
                0
            ]
        },
        {
            "starts": [
                16.0,
                756.0
            ],
            "ends": [
                136.0,
                754.0
            ],
            "time": 15,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                152.0,
                752.0
            ],
            "ends": [
                160.0,
                752.0
            ],
            "time": 1,
            "movement": [
                1,
                0
            ]
        },
        {
            "starts": [
                168.0,
                752.0
            ],
            "ends": [
                185.0,
                745.0
            ],
            "time": 2,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                185.0,
                737.0
            ],
            "ends": [
                185.0,
                721.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                185.0,
                713.0
            ],
            "ends": [
                189.0,
                458.0
            ],
            "time": 32,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                205.0,
                458.0
            ],
            "ends": [
                220.0,
                461.0
            ],
            "time": 1,
            "movement": [
                1,
                1
            ]
        },
        {
            "starts": [
                236.0,
                466.0
            ],
            "ends": [
                244.0,
                466.0
            ],
            "time": 1,
            "movement": [
                1,
                0
            ]
        },
        {
            "starts": [
                256.0,
                461.0
            ],
            "ends": [
                256.0,
                453.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                258.0,
                445.0
            ],
            "ends": [
                256.0,
                429.0
            ],
            "time": 1,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                256.0,
                421.0
            ],
            "ends": [
                256.0,
                413.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                256.0,
                397.0
            ],
            "ends": [
                253.0,
                311.0
            ],
            "time": 11,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                245.0,
                311.0
            ],
            "ends": [
                243.0,
                289.0
            ],
            "time": 2,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                243.0,
                281.0
            ],
            "ends": [
                245.0,
                249.0
            ],
            "time": 4,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                247.0,
                233.0
            ],
            "ends": [
                247.0,
                225.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                247.0,
                217.0
            ],
            "ends": [
                245.0,
                25.0
            ],
            "time": 24,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                245.0,
                20.0
            ],
            "ends": [
                245.0,
                20.0
            ],
            "time": 2,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 157,
    "updated": 1679638405
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/58ff2980-c62c-4d7e-8487-cc7438baff11.json
{
    "id":"58ff2980-c62c-4d7e-8487-cc7438baff11",
    "path": [
        {
            "starts": [
                433.0,
                -1255.0
            ],
            "ends": [
                433.0,
                -1256.0
            ],
            "time": 3,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                433.0,
                -1259.0
            ],
            "ends": [
                429.0,
                -1273.0
            ],
            "time": 1,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                429.0,
                -1289.0
            ],
            "ends": [
                429.0,
                -1297.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                429.0,
                -1313.0
            ],
            "ends": [
                430.0,
                -1353.0
            ],
            "time": 4,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                430.0,
                -1361.0
            ],
            "ends": [
                430.0,
                -1377.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                430.0,
                -1393.0
            ],
            "ends": [
                428.0,
                -1625.0
            ],
            "time": 28,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                428.0,
                -1633.0
            ],
            "ends": [
                428.0,
                -1641.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                425.0,
                -1657.0
            ],
            "ends": [
                423.0,
                -1673.0
            ],
            "time": 2,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                423.0,
                -1681.0
            ],
            "ends": [
                423.0,
                -1697.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                423.0,
                -1705.0
            ],
            "ends": [
                422.0,
                -2345.0
            ],
            "time": 80,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                410.0,
                -2355.0
            ],
            "ends": [
                394.0,
                -2356.0
            ],
            "time": 2,
            "movement": [
                -1,
                0
            ]
        },
        {
            "starts": [
                378.0,
                -2356.0
            ],
            "ends": [
                362.0,
                -2354.0
            ],
            "time": 2,
            "movement": [
                -1,
                1
            ]
        },
        {
            "starts": [
                354.0,
                -2354.0
            ],
            "ends": [
                338.0,
                -2354.0
            ],
            "time": 1,
            "movement": [
                -1,
                0
            ]
        },
        {
            "starts": [
                330.0,
                -2354.0
            ],
            "ends": [
                296.0,
                -2354.0
            ],
            "time": 7,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 161,
    "updated": 1679638791
}
