=== MCDekitateServerRosen/dekitatete-train-data/routes_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "dekitate-train-data Routes Path Validate",
    "description": "Varidate dekitate-train-data path data",
    "properties": {
        "path":{
            "type":"array",
            "items": {
                "type":"object",
                "properties": {
                    "starts":{
                        "type":"array",
                        "items": {
                            "type":"number"
                        }
                    },
                    "ends":{
                        "type":"array",
                        "items": {
                            "type":"number"
                        }
                    },
                    "time":{
                        "type":"integer"
                    },
                    "movement":{
                        "type":"array",
                        "items": {
                            "type":"number"
                        }
                    }
                },
                "required": [
                    "starts",
                    "ends",
                    "time"
                ]
            }
        },
        "id":{
            "type":"string"
        },
        "time":{
            "type":"integer"
        },
        "updated":{
            "type":"integer"
        }
    },
    "required": [
        "id",
        "path",
        "time",
        "updated"
    ]
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/60e9b025-2222-4a54-b21a-ccc95f79a421.json
{
    "id":"60e9b025-2222-4a54-b21a-ccc95f79a421",
    "path": [
        {
            "starts": [
                217.0,
                -4696.0
            ],
            "ends": [
                217.0,
                -4695.0
            ],
            "time": 3,
            "movement": [
                0,
                1
            ]
        },
        {
            "starts": [
                217.0,
                -4688.0
            ],
            "ends": [
                215.0,
                -4673.0
            ],
            "time": 1,
            "movement": [
                -1,
                1
            ]
        },
        {
            "starts": [
                215.0,
                -4666.0
            ],
            "ends": [
                215.0,
                -4659.0
            ],
            "time": 1,
            "movement": [
                0,
                1
            ]
        },
        {
            "starts": [
                215.0,
                -4644.0
            ],
            "ends": [
                214.0,
                -4519.0
            ],
            "time": 16,
            "movement": [
                -1,
                1
            ]
        },
        {
            "starts": [
                209.0,
                -4512.0
            ],
            "ends": [
                185.0,
                -4510.0
            ],
            "time": 2,
            "movement": [
                -1,
                0
            ]
        },
        {
            "starts": [
                177.0,
                -4510.0
            ],
            "ends": [
                151.0,
                -4510.0
            ],
            "time": 4,
            "movement": [
                -1,
                0
            ]
        }
    ],
    "time": 37,
    "updated": 1679639333
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/be4c90bc-f1d2-45a0-9816-edf7ae1ccfe1.json
{
    "id":"be4c90bc-f1d2-45a0-9816-edf7ae1ccfe1",
    "path": [
        {
            "starts": [
                20.0,
                3768.0
            ],
            "ends": [
                21.0,
                3768.0
            ],
            "time": 3,
            "movement": [
                1,
                0
            ]
        },
        {
            "starts": [
                27.0,
                3768.0
            ],
            "ends": [
                45.0,
                3762.0
            ],
            "time": 2,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                44.0,
                3754.0
            ],
            "ends": [
                44.0,
                3746.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                44.0,
                3475.0
            ],
            "ends": [
                44.0,
                3475.0
            ],
            "time": 1,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 50,
    "updated": 1679637836
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/2d3cfaa9-733d-42a9-b558-2e49678a5d79.json
{
    "id":"2d3cfaa9-733d-42a9-b558-2e49678a5d79",
    "path": [
        {
            "starts": [
                149.0,
                -4512.0
            ],
            "ends": [
                154.0,
                -4512.0
            ],
            "time": 3,
            "movement": [
                1,
                0
            ]
        },
        {
            "starts": [
                168.0,
                -4512.0
            ],
            "ends": [
                213.0,
                -4522.0
            ],
            "time": 6,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                213.0,
                -4530.0
            ],
            "ends": [
                213.0,
                -4538.0
            ],
            "time": 1,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                213.0,
                -4554.0
            ],
            "ends": [
                211.0,
                -4682.0
            ],
            "time": 16,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                211.0,
                -4694.0
            ],
            "ends": [
                211.0,
                -4694.0
            ],
            "time": 1,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 39,
    "updated": 1679639388
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/4c7e0503-0762-41f1-8514-7003c8a288b1.json
{
    "id":"4c7e0503-0762-41f1-8514-7003c8a288b1",
    "path": [
        {
            "starts": [
                44.0,
                3002.0
            ],
            "ends": [
                44.0,
                3001.0
            ],
            "time": 4,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                44.0,
                2993.0
            ],
            "ends": [
                43.0,
                2818.0
            ],
            "time": 21,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                38.0,
                2810.0
            ],
            "ends": [
                15.0,
                2807.0
            ],
            "time": 2,
            "movement": [
                -1,
                0
            ]
        },
        {
            "starts": [
                7.0,
                2807.0
            ],
            "ends": [
                -17.0,
                2804.0
            ],
            "time": 2,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                -23.0,
                2797.0
            ],
            "ends": [
                -24.0,
                2773.0
            ],
            "time": 2,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -24.0,
                2765.0
            ],
            "ends": [
                -24.0,
                2328.0
            ],
            "time": 58,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 100,
    "updated": 1679638036
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/01024b34-2c2c-4ae7-92bc-822553589e10.json
{
    "id":"01024b34-2c2c-4ae7-92bc-822553589e10",
    "path": [
        {
            "starts": [
                -97.0,
                4139.0
            ],
            "ends": [
                -97.0,
                4136.0
            ],
            "time": 3,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -97.0,
                4130.0
            ],
            "ends": [
                -95.0,
                3775.0
            ],
            "time": 44,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                -81.0,
                3768.0
            ],
            "ends": [
                -73.0,
                3768.0
            ],
            "time": 1,
            "movement": [
                1,
                0
            ]
        },
        {
            "starts": [
                20.0,
                3768.0
            ],
            "ends": [
                20.0,
                3768.0
            ],
            "time": 1,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 71,
    "updated": 1679637778
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/033ed53e-b78c-4473-9cfc-23012d864e10.json
{
    "id":"033ed53e-b78c-4473-9cfc-23012d864e10",
    "path": [
        {
            "starts": [
                296.0,
                -2354.0
            ],
            "ends": [
                291.0,
                -2354.0
            ],
            "time": 3,
            "movement": [
                -1,
                0
            ]
        },
        {
            "starts": [
                275.0,
                -2354.0
            ],
            "ends": [
                -85.0,
                -2355.0
            ],
            "time": 45,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                -90.0,
                -2362.0
            ],
            "ends": [
                -92.0,
                -2378.0
            ],
            "time": 2,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -94.0,
                -3566.0
            ],
            "ends": [
                -94.0,
                -3566.0
            ],
            "time": 1,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 207,
    "updated": 1679639002
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/e9a45a6a-17a2-46b5-9f08-86e613620343.json
{
    "id":"e9a45a6a-17a2-46b5-9f08-86e613620343",
    "path": [
        {
            "starts": [
                -24.0,
                2328.0
            ],
            "ends": [
                -24.0,
                2327.0
            ],
            "time": 2,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -24.0,
                1942.0
            ],
            "ends": [
                -24.0,
                1942.0
            ],
            "time": 1,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 56,
    "updated": 1679638100
}

=== MCDekitateServerRosen/dekitatete-train-data/routes/865b96aa-4810-47dc-8dd2-16995ae37cbb.json
{
    "id":"865b96aa-4810-47dc-8dd2-16995ae37cbb",
    "path": [
        {
            "starts": [
                -24.0,
                1942.0
            ],
            "ends": [
                -24.0,
                1938.0
            ],
            "time": 2,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -24.0,
                1930.0
            ],
            "ends": [
                -26.0,
                1827.0
            ],
            "time": 12,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                -28.0,
                1819.0
            ],
            "ends": [
                -66.0,
                1610.0
            ],
            "time": 26,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -66.0,
                1602.0
            ],
            "ends": [
                -67.0,
                1522.0
            ],
            "time": 10,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                -75.0,
                1518.0
            ],
            "ends": [
                -93.0,
                1481.0
            ],
            "time": 5,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -93.0,
                1473.0
            ],
            "ends": [
                -87.0,
                1039.0
            ],
            "time": 54,
            "movement": [
                1,
                -1
            ]
        },
        {
            "starts": [
                -79.0,
                1039.0
            ],
            "ends": [
                -66.0,
                1028.0
            ],
            "time": 2,
            "movement": [
                0,
                -1
            ]
        },
        {
            "starts": [
                -66.0,
                1020.0
            ],
            "ends": [
                -67.0,
                948.0
            ],
            "time": 8,
            "movement": [
                -1,
                -1
            ]
        },
        {
            "starts": [
                -67.0,
                948.0
            ],
            "ends": [
                -67.0,
                948.0
            ],
            "time": 1,
            "movement": [
                0,
                0
            ]
        }
    ],
    "time": 137,
    "updated": 1679638245
}
